FROM alpine

LABEL org.opencontainers.image.authors="dmitry.ustalov@gmail.com"

ENV BUNDLE_DISABLE_VERSION_CHECK=1 BUNDLE_VERSION=system JEKYLL_ENV=production JEKYLL_NO_BUNDLER_REQUIRE=1 RUBYGEMS_PREVENT_UPDATE_SUGGESTION=1 RUBYOPT="--disable-did_you_mean"

RUN --mount=type=cache,target=/var/cache/apk \
apk add libffi ruby ruby-bundler && \
apk add --virtual .gem-installdeps build-base ruby-dev libffi-dev && \
gem install -N --conservative --minimal-deps --platform=ruby google-protobuf && \
gem install -N --conservative --minimal-deps jekyll jekyll-feed jekyll-seo-tag jekyll-sitemap && \
gem sources -c && \
apk del .gem-installdeps

CMD ["jekyll", "build"]
