FROM node:lts-alpine

LABEL org.opencontainers.image.authors="dmitry.ustalov@gmail.com"

ENV NO_UPDATE_NOTIFIER=1

RUN --mount=type=cache,target=/root/.npm \
npm install --global --quiet --no-update-notifier --no-fund lightningcss-cli && \
chown -R "$(id -un):$(id -gn)" "$(npm config get prefix)"

CMD ["lightningcss"]
