FROM --platform=$BUILDPLATFORM alpine AS build

ARG TARGETARCH

SHELL ["/bin/sh", "-o", "pipefail", "-c"]

RUN --mount=type=cache,target=/var/cache/apk \
apk add curl jq && \
ARCH=$([ "$TARGETARCH" = "amd64" ] && echo "x86_64" || echo "aarch64") && \
curl https://api.github.com/repos/wilsonzlin/minify-html/releases/latest | jq -r "first(.assets[] | select(.name | contains(\"${ARCH}-unknown-linux-gnu\"))).browser_download_url" | xargs curl -Lo /minhtml && \
chmod +x /minhtml

FROM ubuntu

LABEL org.opencontainers.image.authors="dmitry.ustalov@gmail.com"

COPY --from=build /minhtml /usr/bin/

CMD ["minhtml"]
