FROM node:alpine

MAINTAINER Dmitry Ustalov <dmitry.ustalov@gmail.com>

RUN \
npm install -g --no-update-notifier --no-fund netlify-cli && \
npm cache clean --no-update-notifier -f && \
chown -R "$(id -un):$(id -gn)" "$(npm config get prefix)" && \
mkdir -p "$HOME/.config/netlify" && \
echo '{"telemetryDisabled": true, "cliId": "00000000-0000-0000-0000-000000000000"}' > "$HOME/.config/netlify/config.json"

CMD netlify deploy --prod -d _site
