FROM node:lts-alpine

LABEL org.opencontainers.image.authors="dmitry.ustalov@gmail.com"
LABEL org.opencontainers.image.source="https://github.com/dustalov/dockerfiles"
LABEL org.opencontainers.image.licenses="Unlicense"

ENV NO_UPDATE_NOTIFIER=1

RUN --mount=type=cache,target=/root/.npm \
npm install --global --quiet --no-update-notifier --no-fund purgecss && \
chown -R "$(id -un):$(id -gn)" "$(npm config get prefix)"

CMD ["purgecss"]
