FROM node:lts-alpine

MAINTAINER Dmitry Ustalov <dmitry.ustalov@gmail.com>

RUN \
npm install --global --quiet --no-update-notifier --no-fund cssnano postcss-cli && \
npm cache clean --silent --no-update-notifier --force && \
chown -R "$(id -un):$(id -gn)" "$(npm config get prefix)"

CMD postcss -u cssnano
