FROM fedora

MAINTAINER Dmitry Ustalov <dmitry.ustalov@gmail.com>

COPY ["stub.tex", "/tmp/texlive-test/stub.tex"]

RUN \
dnf --setopt=install_weak_deps=False -y install make latexmk biber texlive-scheme-full glibc-langpack-en && \
cd /tmp/texlive-test && \
latexmk -pdf -silent stub && \
latexmk -lualatex -silent stub && \
rm -rf /tmp/texlive-test && \
dnf clean all
